// <auto-generated>
//     This code was generated by make_version.sh on Mon Jan 13 14:01:28 MSK 2025
//     Do not edit - do not add to git
#pragma once

#define BUILD_VERSION "v1.55.34\nbuilt 2025-01-13 14:01:28 by al.v.gavrikov on macbook-DWRQXWHH23 with Darwin 24.2.0"
